"""Pydantic v2 schemas."""

from app.schemas.business import (
    AdminCreate,
    AdminRead,
    BusinessCreate,
    BusinessRead,
    BusinessUpdate,
    CredentialsRead,
    CredentialsUpdate,
)
from app.schemas.common import APIResponse, MessageResponse, PageMeta, PaginationParams
from app.schemas.content import (
    BulkStatusUpdate,
    ContentItemCreate,
    ContentItemFilter,
    ContentItemRead,
    ContentItemUpdate,
    ContentPlanCreate,
    ContentPlanDetail,
    ContentPlanRead,
    ContentPlanUpdate,
    CopyOutput,
    EditorOutput,
    PlanSlot,
    StrategyOutput,
    VoiceInstruction,
)
from app.schemas.generation import (
    AnalyticsSummary,
    BusinessAnalytics,
    GenerateItemRequest,
    GeneratePlanRequest,
    GenerationTaskResponse,
    RegenerateRequest,
)
from app.schemas.knowledge_base import KnowledgeBaseRead, KnowledgeBaseUpdate, KnowledgeExtraction
from app.schemas.prompt import PromptTemplateCreate, PromptTemplateRead, PromptTemplateUpdate

__all__ = [
    "APIResponse",
    "AdminCreate",
    "AdminRead",
    "AnalyticsSummary",
    "BulkStatusUpdate",
    "BusinessAnalytics",
    "BusinessCreate",
    "BusinessRead",
    "BusinessUpdate",
    "ContentItemCreate",
    "ContentItemFilter",
    "ContentItemRead",
    "ContentItemUpdate",
    "ContentPlanCreate",
    "ContentPlanDetail",
    "ContentPlanRead",
    "ContentPlanUpdate",
    "CopyOutput",
    "CredentialsRead",
    "CredentialsUpdate",
    "EditorOutput",
    "GenerateItemRequest",
    "GeneratePlanRequest",
    "GenerationTaskResponse",
    "KnowledgeBaseRead",
    "KnowledgeBaseUpdate",
    "KnowledgeExtraction",
    "MessageResponse",
    "PageMeta",
    "PaginationParams",
    "PlanSlot",
    "PromptTemplateCreate",
    "PromptTemplateRead",
    "PromptTemplateUpdate",
    "RegenerateRequest",
    "StrategyOutput",
    "VoiceInstruction",
]
